services:
  - type: web
    name: rog-metadata-api
    runtime: node
    region: singapore
    plan: starter
    buildCommand: yarn install && yarn build
    startCommand: node index.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
